INSERT INTO `_shoppingcart`.`Product` (`idProduct`, `productName`, `price`, `description`, `category`) 
	VALUES 	('1', 'Round Table 1', '800', 'Low Quality - Medium Size', 'Furniture'),
			('2', 'Round Table 2', '1200', 'High Quality - Medium Size', 'Furniture'),
			('3', 'Round Table 3', '2000', 'High Quality - Big Size', 'Furniture'),
			('4', 'Square Table 1', '600', 'Low Quality - Little Size', 'Furniture'),
			('5', 'Square Table 2', '900', 'Low Quality - Medium Size', 'Furniture'),
			('6', 'Square Table 3', '2000', 'High Quality - Big Size', 'Furniture'),
			('7', 'Rectangular Table 1', '700', 'Low Quality - Medium Size', 'Furniture'),
			('8', 'Rectangular Table 2', '1600', 'High Quality - Medium Size', 'Furniture'),
			('9', 'Rectangular Table 3', '1700', 'Medium Quality - Medium Size', 'Furniture'),
			('10', 'Chair 1', '400', 'Low Quality', 'Furniture'),
			('11', 'Chair 2', '600', 'Medium Quality', 'Furniture'),
			('12', 'Chair 3', '800', 'High Quality', 'Furniture'),
			('13', 'Microwaves 1', '2100', 'Microwaves Wirphool', 'Electronics'),
			('14', 'Microwaves 2', '2200', 'Microwaves Samsung', 'Electronics'),
			('15', 'Microwaves 3', '2000', 'Microwaves Philco', 'Electronics'),
			('16', 'TV 1', '2000', 'TV Samsung', 'Electronics'),
			('17', 'TV 2', '2000', 'TV LG', 'Electronics'),
			('18', 'TV 3', '2000', 'TV Pionner', 'Electronics'),
			('19', 'Flower Vase 1', '20', 'So cute', 'Accessories'),
			('20', 'Flower Vase 2', '30', 'More cute', 'Accessories'),
			('21', 'Flower Vase 3', '40', 'More more cute', 'Accessories');